apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: enforce-default-network-policy
spec:
  rules:
    - name: validate-network-policy
      match:
        resources:
          kinds:
            - Namespace
      generate:
        kind: NetworkPolicy
        name: default-deny-all
        namespace: "{{ request.object.metadata.name }}"
        data:
          spec:
            podSelector: {}
            policyTypes:
              - Ingress
              - Egress
