apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: app1-pdb
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: app1
      env: dev
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: app2-pdb
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: app2
      env: dev